# This file controls the SlackApp2 PYEZ system to enable the commands within a
# specific channel. You will need to put your specific values in each of the
# variable placeholders.

[app]
    name = "..."

    # from Settings | Basic Information page | App Credentials section
    client_id = "..."
    client_secret = "..."
    signing_secret = "..."
    token = "xoxb-..."
    bot_name = "..."


# The channel ID value that is need for command processing can be obtained via
# https://api.slack.com/methods/conversations.list/test using the type field
# set to "private_channel"
#
#{
#    "ok": false,
#    "error": "missing_scope",
#    "needed": "channels:read,groups:read,mpim:read,im:read",
#    "provided": "identify,chat:write"
#}

[[channels]]
    name = "<channel-name>"
    id = "<channel-ID>"

    # from Features | Incoming Webhooks page
    webhook = "https://hooks.slack.com/services/..."

# The sections section is used to define where the session database is stored.
# You can leave this as it is, and if you're curious you can look at the
# contents of the file.  This has nothing to do with the Slack API
# specifically.

[sessions]
    path = '<path-to-store-sessiondb>'
